#!/usr/bin/perl

require("travlang.pl");
# require("magyar.pl");
# require("babel.pl");

printf("Translating: ");
printf($ARGV[0]);
printf "\n";

&travlang::travlang('to', 'fi', $ARGV[0]);
# &magyar::magyar("to", $ARGV[0]);
# &babel::babelfish('to', 'de', 'test script');
