#!/bin/sh

# Set these paths appropriately

BIN=/home/opus/bin
CMD=/home/opus/cmd
LIB=/home/opus/lib

GERMANTAGGER=${CMD}/tree-tagger-german
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/german-chunker.par
FILTER=${CMD}/filter-chunker-output.perl

$GERMANTAGGER $* |
perl -nae 'if ($#F==0){print}else{print "$F[0]-$F[1]\n"}' |
$TAGGER $PARFILE -token -sgml -eps 0.00000001 -quiet |
$FILTER
